version: '2.1'
services:
    # traefik:
    #     image: traefik:2.5
    #     command:
    #         - --providers.docker
    #         - --entrypoints.web.address=:80
    #     ports:
    #         - 80:80
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock:ro
    #     restart: unless-stopped
    #     networks:
    #         adhoc:
    dns:
        image: cytopia/bind
        environment:
            WILDCARD_DNS: local=172.20.0.1
        ports:
            - 127.0.0.10:53:53/tcp
            - 127.0.0.10:53:53/udp
        networks:
            adhoc:
                ipv4_address: 172.20.0.10
    # aeroo:
    #     image: adhoc/aeroo-docs
    #     restart: unless-stopped

networks:
    adhoc:
        external: false
        name: adhoc
        ipam:
            config:
                - subnet: 172.20.0.0/24
